export enum Permission {
  CREATE_CONTENT = 'CREATE_CONTENT',
  DELETE_CONTENT = 'DELETE_CONTENT',
  READ_CONTENT = 'READ_CONTENT',
  CHANGE_MODE = 'CHANGE_MODE',
  PLAY_MEDIA = 'PLAY_MEDIA',
  STOP_MEDIA = 'STOP_MEDIA',
  PAUSE_MEDIA = 'PAUSE_MEDIA',
  RESUME_MEDIA = 'RESUME_MEDIA',
  UPDATE_POSITION_MEDIA = 'UPDATE_POSITION_MEDIA',
  CLEAR_QUEUE = 'CLEAR_QUEUE',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',
}
